Anpassung an gcc 4.6 (64bit)
git-svn-id: http://subversion.sos/svn/sos/scheduler/engine@17184 c11b8382-0eeb-0310-9acf-d3b3cacd313b

diff --git a/opensource/kernel-cpp/make/make-scheduler-phase b/opensource/kernel-cpp/make/make-scheduler-phase
--- a/opensource/kernel-cpp/make/make-scheduler-phase
+++ b/opensource/kernel-cpp/make/make-scheduler-phase
@@ -13,8 +13,8 @@ set -o errexit
 cmd="$1"
 [ -n "$cmd" ] || fail "Missing first command argument: clean or compile"
 
-platform="$2"
-[ -n "$platform" ] || fail "Missing second command argument: Win32 or x64"
+cpuArchitecture="$2"
+[ -n "$cpuArchitecture" ] || fail "Missing second command argument: Win32 or x64"
 
 configurations="$3 $4"
 [ -n "$3" ] || fail "Missing third command argument: Debug or Release"
@@ -27,12 +27,13 @@ echo Build for operating system $os
 inWindows=$(if [ "$os" == "windows" ]; then echo 1; else echo ""; fi)
 vcbuild=""
 msbuild=""
+visualStudioPlatform=$(if [ "$cpuArchitecture" == "x86" ]; then echo "Win32"; else echo "$cpuArchitecture"; fi)
 
 [ "${PWD/ /_}" == "$PWD" ] || fail "Der Verzeichnispfad darf kein Blank enthalten (vielleicht ist es ein Jenkins-Job mit Blank im Namen?)"
 
 if [ -z "$MAKE_JOBS" ]; then :
     MAKE_JOBS=1
-    if [ -s /proc/cpuinfo ]; then :
+    if [ -e /proc/cpuinfo ]; then :
       MAKE_JOBS=`cat /proc/cpuinfo | grep -w '^processor'|wc -l`
       [ $MAKE_JOBS -le 0 ]  &&  MAKE_JOBS=1
       [ $MAKE_JOBS -gt 8 ]  &&  MAKE_JOBS=8
@@ -68,25 +69,25 @@ function cmd_generic_compile() {
 function cmd_windows_clean() {
     cmd_windows_cleanWithRm
     visualStudio_clean scheduler
-	if [ "$platform" == "Win32" ]; then :
-		visualStudio_clean spidermonkey
-	fi
+    if [ "$cpuArchitecture" == "x86" ]; then :
+        visualStudio_clean spidermonkey
+    fi
     cmd_windows_cleanWithRm
 }
 
 function cmd_windows_cleanWithRm() {
     # Weil "vcbuild.exe /clean" nicht immer löschen kann (Fehlermeldung PRJ0008), siehe http://msdn.microsoft.com/en-us/library/hk8k8k4h%28v=vs.80%29.aspx
     for c in $configurations; do :
-        PATH=/bin find -type d -ipath "*/$platform/$c" -execdir sh -c "rm -rf {}" \; -prune
+        PATH=/bin find -type d -ipath "*/$visualStudioPlatform/$c" -execdir sh -c "rm -rf {}" \; -prune
     done
     rm -rf {bin,bind,ipch}/*
 }
 
 function cmd_windows_compile() {
     visualStudio_compile scheduler
-	if [ "$platform" == "Win32" ]; then :
-		visualStudio_compile spidermonkey
-	fi
+    if [ "$cpuArchitecture" == "x86" ]; then :
+        visualStudio_compile spidermonkey
+    fi
 }
 
 function visualStudio_clean() {
@@ -101,19 +102,22 @@ function visualStudio_compile() {
 
 function msbuild() {
     for c in $configurations; do :
-        echo $msbuild /nologo /m:$NUMBER_OF_PROCESSORS /property:Configuration="$c" /property:Platform="$platform" $*
-        "$msbuild" /nologo /m:$NUMBER_OF_PROCESSORS /property:Configuration="$c" /property:Platform="$platform" $*
+        echo $msbuild /nologo /m:$NUMBER_OF_PROCESSORS /property:Configuration="$c" /property:Platform="$visualStudioPlatform" $*
+        "$msbuild" /nologo /m:$NUMBER_OF_PROCESSORS /property:Configuration="$c" /property:Platform="$visualStudioPlatform" $*
     done
 }
 
 #---------------------------------------------------------------------------------------------Linux
 
 function cmd_linux_clean() {
-    make clean
+    cpuArchitecture=$cpuArchitecture make clean
 }
 
 function cmd_linux_compile() {
-    make scheduler spidermonkey
+    cpuArchitecture=$cpuArchitecture make scheduler
+    if [ "$cpuArchitecture" == "x86" ]; then :
+        cpuArchitecture=$cpuArchitecture make spidermonkey
+    fi
     provide_binaries_as_resources
 }
 
